### ISSUE TITLE
readaloudoptions not working

### ISSUE THREAD

**Issue by graham83** [microsoft/immersive-reader-sdk#391] opened 2022-10-22 06:27 UTC
Configuring readAloudOptions on launch does not have any effect.

Have tried variations of this (e.g. autoplay -> autoPlay, male -> Male without success. The reader opens and requires manual starting and configuration.

Browsers tested Chrome, Edge.

This is the JS configuration:
    
```
const options = {
        "readAloudOptions": {
            "autoplay": true,
            "voice": 'male'
        },
        "onExit": exitCallback,
        "uiZIndex": 1000000
    };
```

**Comment by rwallerms** [comment] 2022-10-26 23:39
Hello graham83,

Unfortunately, we are not able to reproduce this issue on our end. We have confirmed that using your options code above works in our Sample app [here](https://github.com/microsoft/immersive-reader-sdk/blob/471c242f1c08c38892197b8e7b3ad1328736c3be/js/samples/quickstart-csharp/Views/Home/Index.cshtml#L106). Have you tried using our sample to reproduce this?

What is the language of the text are you using? Wondering if it could be related to your language or content somehow, perhaps a language that is not supported for Playback...

Can you share your sample text? Or even perhaps a small project that reproduces the issue, if that is convenient?


Thanks!

**Comment by graham83** [comment] 2022-11-01 02:25
Thank you for your response. I spun up the example and see it is working.
I added option
                            lang: "en-US" to my code and then the autoplay
worked. However removing this option it continues to work so not a definite
bug.. perhaps something cached. I will close this issue thank you.

**Comment by rwallerms** [comment] 2022-11-02 19:30
Thank you for confirming! I will close this issue now. Please reach out with any further questions!

**Closed by rwallerms** 2022-11-02 19:30 UTC
